### ISSUE TITLE
MQTT password field should be text, not number

### ISSUE THREAD

**Issue by ndbroadbent** [nicko88/HTFanControl#20]
I have the web UI running, and I am unable to configure my MQTT password because I use a string (not just numbers):

<img width="1289" alt="Screen Shot 2022-12-22 at 10 35 32 PM" src="https://user-images.githubusercontent.com/139536/209104393-e18ce493-a440-4f2a-b00f-cf711dad07bb.png">

**Comment by nicko88** [comment]
Oops, copy-paste error I supposed.  I'll get this fixed.

For the time being, I think you should be able to put something in the box to create the json node, and then manually put a string in the json file.  The underlying variables should already be strings. 

It might get removed if you modify the settings again after manually inputting your password into the json file.

**Comment by nicko88** [comment]
This is fixed here and deployed in latest pre-release build.

https://github.com/nicko88/HTFanControl/commit/21cddd8516d6ff7efdb00b19ffbb561a0e0ca15f
